[package]
name = "pingora-demo"
version = "0.1.0"
edition = "2024"

[features]
default = ["multi-tier"]
multi-tier = []

[dependencies]
async-trait = "0.1"
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt", "sync"] }
